### ISSUE TITLE
lighthttpd configuration

### ISSUE THREAD

**Issue by ghost** [maciejjankowski/adblock-meets-privoxy-miniweb#1]
Q: 2. Install lighttpd or apache or nginx 3. Update web server config

Can you help me with lighttpd configuration?

**Comment by ghost** [comment]
*ping* thanks for your advice

**Comment by maciejjankowski** [comment]
please refer to the [docs for lighttpd](http://redmine.lighttpd.net/projects/lighttpd/wiki)
and read more on the [original project](https://projects.zubr.me/wiki/adblock2privoxy)

**Comment by ghost** [comment]
omg, are you serious? fortunately there are people who living open source!
